name: check
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run ${{ matrix.tox_env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - type
          - dev
          - readme
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Set up uv for tox
        uses: yezz123/setup-uv@v4
      - name: Set up python for tox
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tox-uv
        run: uv pip install tox tox-uv --system
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up ${{ startsWith(matrix.tox_env, '3.') && matrix.tox_env || '3.12' }} for test
        uses: actions/setup-python@v5
        with:
          python-version: ${{ startsWith(matrix.tox_env, '3.') && matrix.tox_env || '3.12' }}
      - name: Set up test environment
        run: tox -vv -e ${{ matrix.tox_env }} --notest
      - name: Run test environment
        run: tox -e  ${{ matrix.tox_env }} --skip-pkg-install
        env:
          PYTEST_ADDOPTS: "-vv --showlocals"
